[project]
name = "init-project"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
  "numpy==1.26.4",
  "meson-python>=0.15.0,<0.16.0", # required to build numpy
  "xlsxwriter",
]

[tool.uv.workspace]
members = []
